## CircleCI Config with Docker Compose

version: 2
jobs:
  # Name of the job
  build:
    machine: node: version: 6.9.1
    steps:
      - checkout
      - run:
          name: Replace Auth0 test credentials
          command: |
            mv $AUTH0_CFG.example $AUTH0_CFG
            sed -i "s/{CLIENT_ID}/$AUTH0_TEST_CLIENT_ID/g" $AUTH0_CFG
            sed -i "s/{DOMAIN}/$AUTH0_TEST_DOMAIN/g" $AUTH0_CFG
          environment:
            AUTH0_CFG: project/01-Login/src/app/auth/auth0-variables.ts ## This file path should be parametrized
      # build the application image and run detached
      - run: docker build -t quickstart ./project/01-Login/
      - run: docker run -p 3000:3000 -d quickstart

      # prepare tests
      - run: 
          name: Prepare test dependencies
          command: git clone https://github.com/lbalmaceda/webapp-tests-scripts test
      - restore_cache:
          keys:
            - npm-tests-{{ checksum "test/package-lock.json" }}
      - run: 
          command: |
            npm install
            mkdir out
          working_directory: test
      - save_cache:
          key: npm-tests-{{ checksum "test/package-lock.json" }}
          paths:
            - tests/node_modules

      # curl
      - run: 
          name: Wait Web App to respond...
          command: curl --retry 7 http://localhost:3000 #--retry-connrefused

      # tests
      - run: 
          name: Run tests
          command: node ./test/test.js
      - store_artifacts:
          path: ~/out